import Head from "next/head";
import Link from "next/link";
import { Fragment } from "react";
import moment from "moment";

import PostCard from "../components/PostCard";
import Navbar from '../components/Navbar'

const Home = () => {
  return (
    <>
    <Navbar />
    <div className="pt-12">
      <Head>
        <title>Reddit App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container pt-4 flex">
        {/* Posts */}
        <div className="w-160">
          {/* {loading ? ( */}
            {/* <div>Loading...</div> */}
          {/* ) : !data ? ( */}
            {/* <div>No Posts</div> */}
          {/* ) : ( */}
            <>
              {/* <div>
                {data.getPosts.map((post) => (
                  <PostCard post={post} />
                ))}
              </div> */}
            </>
          {/* )} */}
        </div>
        {/* Sidebar */}
      </div>
    </div>
    </>
  );
}

export default Home