import Head from "next/head";
import Link from "next/link";
import { Fragment } from "react";
import moment from "moment";

import { useGetPostsQuery } from "../generated/graphql";
import PostCard from "../components/PostCard";
import { withApollo } from "../utils/withApollo";

const Home = () => {
  const { data, loading } = useGetPostsQuery();
  // console.log(data?.getPosts);

  return (
    <div className="pt-12">
      <Head>
        <title>Reddit App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container pt-4 flex">
        {/* Posts */}
        <div className="w-160">
          {loading ? (
            <div>Loading...</div>
          ) : !data ? (
            <div>No Posts</div>
          ) : (
            <>
              <div>
                {data.getPosts.map((post) => (
                  <PostCard post={post} />
                ))}
              </div>
            </>
          )}
        </div>
        {/* Sidebar */}
      </div>
    </div>
  );
}

export default withApollo({ ssr: false })(Home)