import Head from "next/head";
import Link from "next/link";
import PostCard from "../components/PostCard";
import Navbar from "../components/Navbar";
import { usePostsQuery, useTopSubsQuery } from "../generated/graphql";

const Home = () => {
  const { data, loading } = usePostsQuery();
  const { data: topSubs } = useTopSubsQuery();
  return (
    <>
      <Navbar />
      <div className="pt-12">
        <Head>
          <title>Reddit App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="container pt-4 flex">
          {/* Posts */}
          <div className="w-160">
            {loading ? (
              <div>Loading...</div>
            ) : !data ? (
              <div>No Posts</div>
            ) : (
              <>
                <div>
                  {data.getPosts.map((post) => (
                    <PostCard key={post.id} post={post} />
                  ))}
                </div>
              </>
            )}
          </div>
          {/* Sidebar */}
          {topSubs?.topSubs && <div className="ml-6 w-80">
            <div className="bg-white rounded">
              <div className="p-4 border-b-2">
                <p className="text-lg font-semibold text-center">
                  Top Communities
                </p>
              </div>
              <div>
                {topSubs.topSubs?.map((sub) => (
                  <div
                    key={sub.title}
                    className="flex items-center px-4 py-2 text-xs border-b"
                  >
                    <Link href={`/r/${sub.name}`}>
                      <img
                        src={sub.name}
                        className="w-6 h-6 mr-1 rounded-full cursor-pointer"
                      />
                    </Link>
                    <Link href={`/r/${sub.name}`}>
                      <a className="font-bold hover:cursor-pointer">
                        /r/{sub.name}
                      </a>
                    </Link>
                  </div>
                ))}
              </div>
            </div>
          </div>}
        </div>
      </div>
    </>
  );
};

export default Home;
